### ISSUE TITLE
Unauthorized Error

### ISSUE THREAD

**Issue by novinsab** [gachris/iCloud.Dav#1]
Hi,

I have changed the NetworkCredentials to my own iCloud credentials but keep getting "unauthorized" error in both .Net40 and .NetCore3.1 examples.

How do I fix this problem?

**Comment by gachris** [comment]
Hi, 

You need to create app specific password from here https://support.apple.com/en-us/HT204397

**Comment by novinsab** [comment]
Thanks!

Does it support Gmail and other cardav compatible services?

On Mar 18, 2022, at 10:56 AM, gachris ***@***.***> wrote:

﻿

@hi<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhi&data=04%7C01%7C%7Cf40c6284c63e474cc01708da08ef7d9f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832121944165216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7PCux9nOti6zUkE%2F1fZb9r0%2FVyE4uu8dX0uEgkSdSPk%3D&reserved=0>,

You need to create app specific password from here https://support.apple.com/en-us/HT204397<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.apple.com%2Fen-us%2FHT204397&data=04%7C01%7C%7Cf40c6284c63e474cc01708da08ef7d9f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832121944165216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4OBFpS24hpuuMR4WQ8ZvBKEQmF5fmd3iAMeGwiiQvjk%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgachris%2FiCloud.Dav%2Fissues%2F1%23issuecomment-1072490525&data=04%7C01%7C%7Cf40c6284c63e474cc01708da08ef7d9f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832121944165216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n3zZd2nFwKeZAUK0rqSG1WnbGs3UTv%2Fo3XUNWkTSf9k%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO2ON6YWXCAM3TBY4W4XUMTVASKSBANCNFSM5QTUFHFA&data=04%7C01%7C%7Cf40c6284c63e474cc01708da08ef7d9f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832121944165216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rplL9u%2BE5BknLTAc0F%2B%2BCBlF1AMrDibBB2L%2B9Fr6aXw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf40c6284c63e474cc01708da08ef7d9f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832121944165216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xqtMPSJg9U4k%2Bjazxh9Q2U5Z9b5RMz0hds%2FgX%2BKd%2BJg%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf40c6284c63e474cc01708da08ef7d9f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832121944165216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WEQNMytwWrsfvzTmzS6jFE6xoAWQp7GHYLrm4Vqu6pU%3D&reserved=0>.

**Comment by gachris** [comment]
Hi novinsab,

At the moment, only iCloud service is available.
