### ISSUE TITLE
Docs how to create a new iCloud calendar

### ISSUE THREAD

**Issue by thgossler** [gachris/iCloud.Dav#10]
Hi,

Great project, very helpful!

I want to create a new iCloud calendar with the iCloud.Dav.Calendar library but don't know how. ChatGPT and GitHub Copilot also seem to be confused and are not able to come up with a solution proposal. 

Could you please explain such a scenario in the docs or at least put some working sample code here into an answers?

Thanks a lot!

**Comment by gachris** [comment]
Hello @thgossler,

I have created a simple console app example demonstrating how to create a new calendar. You can find the code in the following link:

https://github.com/gachris/iCloud.Dav.Examples/blob/master/iCloud.Dav.Examples/Program.cs

Feel free to check it out, and let me know if you have any questions or need further clarification!

Best regards,
Christos

**Comment by thgossler** [comment]
Great, thanks! I will try it. 

I think the following two aspects are not intuitive and could be improved.

1. newCalendar.SupportedCalendarComponents.Add("VEVENT");  => I had expected this either by default or to be able to specify it in the constructor or to be able to set the SupportedCalendarComponents property in the initializer.

2. Id = Guid.NewGuid().ToString().ToUpperInvariant()  => may not be needed, at least the Id property is automatically set to GUID value, will see

**Comment by thgossler** [comment]
It is working, thanks!
