### ISSUE TITLE
[Question] - Is it possible to get VEVENT status?

### ISSUE THREAD

**Issue by viavn** [gachris/iCloud.Dav#4]
Hey everyone!

I need to fetch some events by filtering between a start and end date. So far, so good. However, when retrieving the data, I noticed that the VEVENT status is not included, only the attendees statuses. 

Do you know why this happens? What I missing?

**Comment by gachris** [comment]
Hello @viavn 

I'm having difficulty replicating the issue you've described concerning the absence of the VEVENT status when fetching events. To assist you effectively, could you please provide more details, such as the code or a sample VEVENT that you are working with? This information will enable me to provide more targeted assistance.
